services:
#Mysql instance needed for the API
    DB:
        
        image: mysql
        #Name the container
        container_name: mysqlservice
        
        ports:
            - "3307:3306"
        #Environment variables
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: test
 

    #API part
    theapi:
  
        build: ./DB/ProjetFullStack
        
        image: theapi
        
        container_name: theapi
        
        ports:
            - "8080:8080"
        
        environment:
            DATABASE_HOST: mysqlservice
            SOURCE_HOST: client
        
        

    #FrontEnd service using our Angular project image
    client:
        #Build the image from the Dockerfile in indicated path
        build: ./AngularClient
        #From what image pull the service
        image: client
        #Name the container
        container_name: client
        ports:
            - "4200:80"
        #Make the service depend on the SpringBoot service
        depends_on:
            - theapi
